/**
 * AI 使用指南生成文件写入工具。
 *
 * 该模块只负责写入插件拥有的 skill/rule 文件，适用于 Vite dev server 启动时补充 AI 客户端上下文；
 * 通过生成标记保护用户手写文件，避免开发服务启动过程覆盖用户定制内容。
 */
import fs from 'node:fs/promises'
import path from 'node:path'

/** 自动生成文件标记，用于区分插件拥有的文件和用户手写文件。 */
export const GENERATED_SKILL_CONFIG_MARKER =
  '<!-- Generated by vite-plugin-vue-mcp-next. Safe to edit, but automatic updates only apply while this marker remains. -->'

/**
 * 自动生成文本文件写入参数。
 *
 * 使用对象参数是为了后续扩展 dry-run、日志策略或生成来源时不破坏调用方签名。
 */
export interface WriteGeneratedTextFileOptions {
  /** 目标文件路径，调用方负责按客户端规则传入项目级路径。 */
  readonly filePath: string
  /** 完整文件内容，必须包含生成标记才能允许后续自动更新。 */
  readonly content: string
  /** 日志中的目标名称，用于用户定位是哪类客户端配置被跳过。 */
  readonly targetName: string
}

/**
 * 写入插件拥有的生成文件。
 *
 * 只有缺失文件或带生成标记的文件会被写入；没有标记的已有文件视为用户手写内容，
 * 必须跳过以避免启动 Vite 时覆盖用户对 AI 客户端上下文的定制。
 */
export async function writeGeneratedTextFile(
  options: WriteGeneratedTextFileOptions
): Promise<void> {
  try {
    const current = await readOptionalTextFile(options.filePath)

    if (current && !current.includes(GENERATED_SKILL_CONFIG_MARKER)) {
      console.warn(
        `[vite-plugin-vue-mcp-next] Skipped ${options.targetName} at ${options.filePath}: file is not generated by this plugin`
      )
      return
    }

    await fs.mkdir(path.dirname(options.filePath), { recursive: true })
    await fs.writeFile(options.filePath, options.content)
  } catch (error) {
    console.warn(
      `[vite-plugin-vue-mcp-next] Failed to update ${options.targetName} at ${options.filePath}: ${formatError(error)}`
    )
  }
}

/**
 * 读取可选文本文件。
 *
 * 缺失文件表示首次生成，应返回空字符串让调用方继续创建；其他文件系统错误需要交给外层统一记录警告。
 */
async function readOptionalTextFile(filePath: string): Promise<string> {
  try {
    return await fs.readFile(filePath, 'utf-8')
  } catch (error) {
    if (isNodeError(error) && error.code === 'ENOENT') {
      return ''
    }

    throw error
  }
}

/**
 * 格式化未知错误。
 *
 * 文件写入失败只进入 Vite 启动警告，统一转成字符串可以避免 unknown 直接泄漏到日志格式中。
 */
function formatError(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}

/**
 * 判断 Node 文件系统错误。
 *
 * 这里只关心 `ENOENT` 这类 errno 字段，使用窄类型保护可以避免对普通 Error 读取不存在字段。
 */
function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error
}
